language: node_js
node_js:
- "8"
- node

script: echo "Running tests against $(node -v)..."

jobs:
  include:
    - stage: Unit test
      before_script:
        - npm install
      script: 
        - npm test
    - stage: Produce Coverage
      node_js: node
      before_script:
        - npm install
      script: 
        - npm test:coverage
